//! v0.2 Shell bridge — the "Protected Runtime" listener.
//!
//! Listens on a random localhost port. The shell init scripts (generated by
//! `shell_hooks.rs`) POST each command here before execution. The bridge:
//!
//!   1. Parses the command via `policy::classify::classify_shell_command`.
//!   2. Builds an `Action` (Shell/Git/Package category + target=command).
//!   3. Runs `classify_action` to stamp risk + policy decision + reasons.
//!   4. If the decision is `Ask` or the risk is HIGH/CRITICAL (and
//!      `shell_blocking` is on), blocks on the approval gate — emits
//!      `actionguard://approval/request` and waits for the user to resolve
//!      via the `resolve_approval` Tauri command.
//!   5. Records the (now-finalized) action to the ledger.
//!   6. Returns the final decision (`allow` / `deny`) to the shell.

use crate::commands::AppState;
use crate::models::{Action, ApprovalResolution, Decision};
use crate::policy::classify;
use crate::storage;
use serde::{Deserialize, Serialize};
use std::io::{BufRead, BufReader, Read, Write};
use std::net::{TcpListener, TcpStream};
use std::sync::Arc;
use std::time::{Duration, SystemTime};
use tauri::Emitter;

/// Optional Tauri app handle for event emission. When `None`, the bridge
/// runs in standalone (CLI-first) mode: no event emission, but the core
/// classify → policy → approval pipeline works identically.
#[derive(Clone)]
pub enum EmitHandle {
    #[allow(dead_code)]
    Tauri(tauri::AppHandle),
    #[allow(dead_code)] // CLI-first mode uses eprintln fallback; reserved for GUI-less events
    Standalone,
}

impl EmitHandle {
    pub fn emit(&self, event: &str, payload: impl Serialize + Clone) {
        match self {
            EmitHandle::Tauri(app) => {
                let _ = app.emit(event, payload);
            }
            EmitHandle::Standalone => {
                let payload_str = serde_json::to_string_pretty(&payload).unwrap_or_default();
                eprintln!("  actionguard://{event} {payload_str}");
            }
        }
    }
}

/// Handle returned by `Bridge::start`. Carries the port + secret the shell
/// init scripts need to find the listener.
#[allow(dead_code)] // persisted to current.hook; consumed by shell hooks, not Rust
pub struct Bridge {
    pub port: u16,
    pub secret: String,
    pub session_id: String,
}

/// Request body posted by the shell hook.
#[derive(Debug, Deserialize)]
pub struct PreExecRequest {
    pub command: String,
    #[serde(default)]
    pub cwd: Option<String>,
    #[allow(dead_code)] // populated by hooks; reserved for Phase C evidence
    #[serde(default)]
    pub shell: Option<String>,
    #[allow(dead_code)] // populated by hooks; reserved for Phase C evidence
    #[serde(default)]
    pub pid: Option<u32>,
}

/// Response returned by the bridge.
#[derive(Debug, Serialize)]
pub struct PreExecResponse {
    pub decision: String,
    pub risk: String,
    pub matched_rule: Option<String>,
    pub reason: String,
}

impl Bridge {
    /// Bind a localhost listener, write the hook descriptor, and spawn the
    /// accept loop. The returned handle is dropped by the caller — the
    /// listener thread keeps running until the session is torn down.
    ///
    /// Pass `EmitHandle::Standalone` for CLI-first mode (no Tauri GUI).
    /// Pass `EmitHandle::Tauri(app)` for GUI mode (emits events to the UI).
    pub fn start(
        state: Arc<AppState>,
        app: EmitHandle,
        session_id: String,
    ) -> std::io::Result<Bridge> {
        let listener = TcpListener::bind("127.0.0.1:0")?;
        let port = listener.local_addr()?.port();
        let secret = generate_secret();

        // Persist hook descriptor so shells spawned later can find us.
        storage::write_hook_file(&session_id, port, &secret)
            .map_err(|e| std::io::Error::other(e.to_string()))?;
        storage::point_current_hook(&session_id)
            .map_err(|e| std::io::Error::other(e.to_string()))?;

        let secret_clone = secret.clone();
        let session_id_clone = session_id.clone();
        let app_clone = app.clone();
        std::thread::Builder::new()
            .name("actionguard-bridge".to_string())
            .spawn(move || {
                accept_loop(listener, state, app_clone, session_id_clone, secret_clone);
            })?;

        Ok(Bridge {
            port,
            secret,
            session_id,
        })
    }

    /// Tear down: remove the `current.hook` link + drop the closed sentinel
    /// so stale hooks can tell this stop was deliberate and allow the next
    /// command (they fail closed only on *unexpected* failures).
    pub fn stop(&self) {
        storage::teardown_current_hook(&self.session_id);
    }
}

fn accept_loop(
    listener: TcpListener,
    state: Arc<AppState>,
    app: EmitHandle,
    session_id: String,
    secret: String,
) {
    listener
        .set_nonblocking(false)
        .expect("bridge listener blocking");
    for stream in listener.incoming() {
        let stream = match stream {
            Ok(s) => s,
            Err(_) => continue,
        };
        // Stop accepting when the session is gone.
        let alive = {
            let guard = state.session.lock().unwrap();
            guard.as_ref().map(|s| s.id == session_id).unwrap_or(false)
        };
        if !alive {
            return;
        }
        let state = state.clone();
        let app = app.clone();
        let session_id = session_id.clone();
        let secret = secret.clone();
        std::thread::spawn(move || {
            let _ = handle_request(stream, state, app, session_id, secret);
        });
    }
}

fn handle_request(
    stream: TcpStream,
    state: Arc<AppState>,
    app: EmitHandle,
    session_id: String,
    secret: String,
) -> std::io::Result<()> {
    stream.set_read_timeout(Some(Duration::from_secs(5)))?;
    stream.set_write_timeout(Some(Duration::from_secs(5)))?;

    let mut reader = BufReader::new(stream.try_clone()?);
    let mut request_line = String::new();
    reader.read_line(&mut request_line)?;

    // Parse the request line: METHOD PATH HTTP/1.1
    let parts: Vec<&str> = request_line.split_whitespace().collect();
    if parts.len() < 3 {
        return write_response(stream, 400, "bad request");
    }
    let method = parts[0];
    let path = parts[1];

    // Read headers until empty line.
    let mut headers = std::collections::HashMap::new();
    loop {
        let mut line = String::new();
        reader.read_line(&mut line)?;
        if line == "\r\n" || line == "\n" || line.is_empty() {
            break;
        }
        if let Some((k, v)) = line.split_once(':') {
            headers.insert(k.to_lowercase(), v.trim().to_string());
        }
    }

    // Auth check: every request must carry the per-session secret.
    let provided = headers.get("x-actionguard-secret").map(|s| s.as_str()).unwrap_or("");
    if provided != secret {
        return write_response(stream, 401, "unauthorized");
    }

    // Read body using Content-Length.
    let content_length: usize = headers
        .get("content-length")
        .and_then(|s| s.parse().ok())
        .unwrap_or(0);
    let mut body = vec![0u8; content_length];
    if content_length > 0 {
        reader.read_exact(&mut body)?;
    }
    let body_str = String::from_utf8_lossy(&body).to_string();

    // Bail if the session is gone (stale hook).
    let alive = {
        let guard = state.session.lock().unwrap();
        guard.as_ref().map(|s| s.id == session_id).unwrap_or(false)
    };
    if !alive {
        return write_response(stream, 410, "session gone");
    }

    // Dispatch on method + path. POST /preexec is the shell hook; POST /resolve
    // and GET /pending are the headless CLI surface (actionguard allow/deny).
    match (method, path) {
        ("POST", "/preexec") => handle_preexec(stream, state, app, session_id, body_str),
        ("POST", "/resolve") => handle_resolve(stream, state, app, body_str),
        ("GET", "/pending") => handle_pending(stream, state),
        ("GET", "/status") => write_json(stream, &serde_json::json!({"status": "ok"})),
        _ => write_response(stream, 404, "not found"),
    }
}

/// Hot-reload `policies.user.yml` if its mtime changed since the last load.
/// Cheap: a single `stat` per /preexec, no thread needed. The PolicySet is
/// swapped under the write lock so concurrent readers see the new rules on
/// their next `read().unwrap()` call.
fn maybe_reload_user_policy(state: &Arc<AppState>) {
    let path = storage::user_policy_path();
    let Ok(meta) = std::fs::metadata(&path) else {
        return;
    };
    let Ok(mtime) = meta.modified() else {
        return;
    };
    let mtime_nanos = mtime
        .duration_since(SystemTime::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0);
    let last_seen = state.last_policy_mtime.lock().unwrap();
    if *last_seen == mtime_nanos {
        return;
    }
    drop(last_seen);
    // Reload + swap. If the new file fails to parse, the loader logs and
    // returns an empty set — we DON'T want to wipe out built-ins, so we keep
    // the existing set in that case.
    let new_set = crate::policy::load_policy_set();
    if !new_set.rules.is_empty() {
        let mut guard = state.policy.write().unwrap();
        *guard = new_set;
    }
    *state.last_policy_mtime.lock().unwrap() = mtime_nanos;
}

/// Handle POST /preexec from the shell hook.
fn handle_preexec(
    mut stream: TcpStream,
    state: Arc<AppState>,
    app: EmitHandle,
    session_id: String,
    body_str: String,
) -> std::io::Result<()> {
    // Lazy hot-reload of policies.user.yml.
    maybe_reload_user_policy(&state);

    let req: PreExecRequest = match serde_json::from_str(&body_str) {
        Ok(r) => r,
        Err(_) => return write_response(stream, 400, "invalid json"),
    };

    // Classify + build the Action.
    let parsed = classify::classify_shell_command(&req.command);
    let mut action = Action::new_shell(
        req.command.clone(),
        req.cwd.clone(),
        state.config.lock().unwrap().default_agent.clone().into(),
    );
    action.category = parsed.category;
    action.kind = Some(classify::kind_for(&parsed).to_string());

    // 1) Pure classify: stamps risk + policy decision + reasons. Doesn't
    //    touch the ledger yet — we may need to block first.
    crate::commands::classify_action(&state, &mut action);

    // 2) Decide whether the human gate needs to fire.
    //    - Decision::Deny from a policy rule: deny outright, no modal.
    //    - Decision::Ask from a policy rule: ALWAYS fire the gate.
    //    - Decision::Allow + (High|Critical) risk: fire the gate when
    //      shell_blocking is on (catch-all for risky actions no rule covers).
    //    - Otherwise: allow + record.
    //
    // Mode A (Observe): the gate is ALWAYS skipped — we record everything but
    //   never block. This is the "technical honesty" switch: if you're only
    //   watching, you're observing, not protecting.
    //
    // Mode B (Protected): the gate fires for Ask or High/Critical risk.
    let session_mode = {
        let guard = state.session.lock().unwrap();
        guard.as_ref().map(|s| s.mode).unwrap_or_default()
    };
    let cfg_shell_blocking = state.config.lock().unwrap().shell_blocking;
    let cfg_timeout = state.config.lock().unwrap().approval_timeout_secs.max(5);
    let initial_decision = action.decision.unwrap_or(Decision::Allow);
    let risk = action.risk.unwrap_or(crate::models::RiskLevel::Low);
    let needs_approval = session_mode == crate::models::SessionMode::Protected
        && !matches!(initial_decision, Decision::Deny)
        && (initial_decision == Decision::Ask
            || (cfg_shell_blocking
                && matches!(
                    risk,
                    crate::models::RiskLevel::High | crate::models::RiskLevel::Critical
                )));

    let final_decision = if needs_approval {
        // Mark the action as pending while we wait. The ledger will see
        // result="awaiting-approval" until the user resolves.
        action.result = Some("awaiting-approval".to_string());
        // Push a snapshot of the action to the ledger BEFORE blocking so
        // the UI can show "blocked on approval" in real time. The post-
        // resolution record below will carry the final decision.
        crate::commands::bump_counters(&state, &action);
        crate::commands::push_action(&state, action.clone());

        let req = crate::approval::build_request(
            action.clone(),
            session_id.clone(),
            cfg_timeout,
        );
        let rx = state.approvals.request(req.clone());
        // v0.2 — popup telemetry: one interruption per gated action. This is
        // the denominator of User Override Rate (`actionguard stats`).
        {
            let mut guard = state.session.lock().unwrap();
            if let Some(s) = guard.as_mut() {
                s.popups += 1;
            }
        }
        // Notify the frontend. The ApprovalModal subscribes to this event.
        app.emit("actionguard://approval/request", req);

        // Block until the user resolves or the timeout fires. The bridge
        // worker thread is per-request so this doesn't stall other shells.
        let timeout = std::time::Duration::from_secs(cfg_timeout as u64);
        match rx.recv_timeout(timeout) {
            Ok(d) => d,
            // Timeout or store dropped (session ending) — fail-closed,
            // consistent with the hook-side fail-closed default.
            Err(_) => Decision::Deny,
        }
    } else {
        initial_decision
    };

    // Observe mode override: ALWAYS allow, never block. The policy decision
    // (Allow/Ask/Deny) is still in `action.decision` from classify_action, so
    // the ledger shows what WOULD have happened. But the actual execution
    // decision is Allow — the user chose to observe, not protect.
    let final_decision = if session_mode == crate::models::SessionMode::Observe {
        Decision::Allow
    } else {
        final_decision
    };

    // 3) Finalize the action's decision + result, then record it.
    action.decision = Some(final_decision);
    action.result = Some(if matches!(final_decision, Decision::Deny) {
        "blocked".to_string()
    } else if session_mode == crate::models::SessionMode::Observe {
        "executed (observe)".to_string()
    } else {
        "executed".to_string()
    });

    // When the approval path already pushed (needs_approval), we DON'T push
    // again — instead we patch the existing ledger row by re-pushing with
    // the same id. The push_action dedupe is keyed on (action_kind, path)
    // for File actions only, so shell actions append a fresh row. To keep
    // the ledger tidy we replace the pending row's id with this one — but
    // because the ledger is append-only NDJSON, we can't actually rewrite.
    // For v0.2 the "awaiting-approval" + final rows both exist; the UI
    // collapses them via id grouping. (Phase D will add a proper update
    // mechanism.)
    if !needs_approval {
        crate::commands::bump_counters(&state, &action);
        crate::commands::push_action(&state, action.clone());
    } else {
        // The bridge already pushed the pending row above. Re-emit so the
        // final state shows up. We can't dedupe — append the resolution row.
        //
        // v0.2 — user behavior telemetry (local-only): stamp whether the user
        // overrode the gate, and when the popup was dismissed. This is the
        // data behind User Override Rate in `actionguard stats`.
        let is_override = matches!(final_decision, Decision::Allow)
            && matches!(initial_decision, Decision::Ask);
        action.user_override = Some(is_override);
        action.resolved_at = Some(crate::models::now_str());
        if is_override {
            let mut guard = state.session.lock().unwrap();
            if let Some(s) = guard.as_mut() {
                s.overrides += 1;
            }
        }
        crate::commands::push_action(&state, action.clone());
    }

    // 4) Build the response the shell hook will read.
    let decision_str = match final_decision {
        Decision::Allow => "allow",
        // Ask shouldn't reach here (it's converted to Allow/Deny by the
        // approval flow). Fail-safe to deny if it does.
        Decision::Ask => "deny",
        Decision::Deny => "deny",
    };
    let resp = PreExecResponse {
        decision: decision_str.to_string(),
        risk: action
            .risk
            .map(|r| r.as_str().to_string())
            .unwrap_or_else(|| "low".to_string()),
        matched_rule: action.matched_rule.clone(),
        reason: action.reasons.join("; "),
    };

    let body = serde_json::to_string(&resp).unwrap_or_else(|_| "{}".to_string());
    let http = format!(
        "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        body.len(),
        body
    );
    stream.write_all(http.as_bytes())?;
    stream.flush()?;
    Ok(())
}

fn write_response(mut stream: TcpStream, code: u16, msg: &str) -> std::io::Result<()> {
    let body = format!("{{\"error\":\"{}\"}}", msg);
    let http = format!(
        "HTTP/1.1 {} OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        code,
        body.len(),
        body
    );
    stream.write_all(http.as_bytes())?;
    stream.flush()?;
    Ok(())
}

/// Write a 200 OK with a JSON body. Used for the /pending and /status endpoints.
fn write_json<T: Serialize>(mut stream: TcpStream, body: &T) -> std::io::Result<()> {
    let body = serde_json::to_string(body).unwrap_or_else(|_| "{}".to_string());
    let http = format!(
        "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        body.len(),
        body
    );
    stream.write_all(http.as_bytes())?;
    stream.flush()?;
    Ok(())
}

/// Handle POST /resolve — headless CLI allow/deny. Mirrors the
/// `resolve_approval` Tauri command. The body is an `ApprovalResolution`.
fn handle_resolve(
    stream: TcpStream,
    state: Arc<AppState>,
    app: EmitHandle,
    body_str: String,
) -> std::io::Result<()> {
    let resolution: ApprovalResolution = match serde_json::from_str(&body_str) {
        Ok(r) => r,
        Err(_) => return write_response(stream, 400, "invalid json"),
    };

    let ApprovalResolution {
        approval_id,
        decision,
        learn_rule,
    } = resolution;

    // 1) Wake the bridge waiter. If unknown/expired, tell the CLI.
    if state
        .approvals
        .resolve(&approval_id, decision)
        .is_err()
    {
        return write_response(stream, 404, "approval not found or expired");
    }

    // 2) Persist the learned rule + hot-swap the policy set.
    if let Some(mut rule) = learn_rule {
        rule.source = crate::models::PolicySource::User;
        if rule.id.is_empty() {
            rule.id = format!(
                "user-{}-{}",
                rule.match_
                    .category
                    .map(|c| c.as_str())
                    .unwrap_or("any"),
                rule.match_.command.as_deref().unwrap_or("any")
            );
        }
        // append_user_rule_and_reload is private in commands.rs; replicate
        // its 3-step flow here so the CLI can drive "Always deny" headlessly.
        let mut file: crate::models::PolicyFile = storage::load_policies_user();
        file.rules.retain(|r| r.id != rule.id);
        file.rules.push(rule);
        if storage::save_policies_user(&file).is_ok() {
            let new_set = crate::policy::load_policy_set();
            if !new_set.rules.is_empty() {
                let mut guard = state.policy.write().unwrap();
                *guard = new_set;
            }
        }
    }

    // 3) Notify the frontend so the modal closes.
    let payload = ApprovalResolution {
        approval_id,
        decision,
        learn_rule: None,
    };
    app.emit("actionguard://approval/resolved", payload);

    write_json(
        stream,
        &serde_json::json!({
            "status": "resolved",
            "decision": match decision {
                Decision::Allow => "allow",
                Decision::Ask => "ask",
                Decision::Deny => "deny",
            }
        }),
    )
}

/// Handle GET /pending — list pending approvals for the CLI's interactive
/// `allow`/`deny` picker. Body is a JSON array of `ApprovalRequest`.
fn handle_pending(stream: TcpStream, state: Arc<AppState>) -> std::io::Result<()> {
    let pending = state.approvals.list();
    write_json(stream, &pending)
}

/// Random 32-char hex secret. Not cryptographically secure against a local
/// attacker with process injection, but sufficient to prevent cross-session
/// snooping from another local process.
fn generate_secret() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let mut s = String::with_capacity(32);
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let pid = std::process::id() as u128;
    let mix = nanos ^ (pid << 32) ^ (port_entropy() as u128);
    for i in 0..8 {
        let chunk = (mix >> (i * 16)) & 0xFFFF;
        s.push_str(&format!("{:04x}", chunk));
    }
    s
}

fn port_entropy() -> u64 {
    // Mix in some additional entropy from the OS — the address of a freshly
    // bound socket. Good enough for a non-cryptographic local secret.
    std::net::TcpListener::bind("127.0.0.1:0")
        .and_then(|l| l.local_addr().map(|a| a.port() as u64))
        .unwrap_or(0)
}
