use std::path::Path;
use std::process::Command;

use crate::shell_hooks;

/// Open a terminal window whose working directory is `workspace` and which
/// has sourced the ActionGuard shell hook for `session_id`.
///
/// The hook script is generated by `shell_hooks::write_for_session` before
/// this is called (see `commands::start_session`). On startup the shell
/// reads `~/.actionguard/sessions/current.hook` to find the bridge port +
/// secret, then installs a pre-execution hook that POSTs each command to
/// the bridge for risk + policy evaluation.
///
/// The command is best-effort — if no terminal can be spawned we still
/// continue the session (the watcher + bridge work regardless).
pub fn open_terminal(workspace: &Path, session_id: &str, shell: &str) -> std::io::Result<()> {
    // The init script must already exist (start_session wrote it). If it's
    // missing we still open the terminal but without interception — the
    // session won't be blocked, only file-watch works.
    let init_script = shell_hooks::init_script_path(session_id, shell);
    let have_init = init_script.exists();

    #[cfg(target_os = "windows")]
    {
        open_windows(workspace, &init_script, have_init, shell)?;
    }
    #[cfg(target_os = "macos")]
    {
        open_macos(workspace, &init_script, have_init, shell)?;
    }
    #[cfg(target_os = "linux")]
    {
        open_linux(workspace, &init_script, have_init, shell)?;
    }
    Ok(())
}

#[cfg(target_os = "windows")]
fn open_windows(
    workspace: &Path,
    init_script: &Path,
    have_init: bool,
    shell: &str,
) -> std::io::Result<()> {
    use std::os::windows::process::CommandExt;

    // CREATE_NEW_CONSOLE = 0x00000010 — spawn a fresh console window.
    const CREATE_NEW_CONSOLE: u32 = 0x0000_0010;

    let dir = workspace.to_string_lossy().replace('\'', "''");

    // We always launch powershell.exe on Windows (PowerShell is the only
    // shell we generate a hook for). The script both `Set-Location`s into
    // the workspace and sources the ActionGuard hook.
    let script = if have_init {
        let init_path = init_script.to_string_lossy().replace('\'', "''");
        format!(
            ". '{init_path}'; Set-Location -LiteralPath '{dir}'"
        )
    } else {
        format!("Set-Location -LiteralPath '{dir}'")
    };

    let _ = shell; // currently unused — always powershell on Windows.
    Command::new("powershell.exe")
        .args(["-NoExit", "-Command", &script])
        .creation_flags(CREATE_NEW_CONSOLE)
        .spawn()?;
    Ok(())
}

#[cfg(target_os = "macos")]
fn open_macos(
    workspace: &Path,
    init_script: &Path,
    have_init: bool,
    shell: &str,
) -> std::io::Result<()> {
    let dir = workspace.to_string_lossy();
    let init_path = init_script.to_string_lossy();

    // macOS Terminal.app always opens a login shell. We tell AppleScript to
    // run the user's default shell (zsh by default), source our hook, then
    // cd into the workspace. `exec` keeps the shell as the front process.
    let cmd = if have_init {
        format!("source '{init_path}' 2>/dev/null; cd '{dir}' && exec {shell} -l")
    } else {
        format!("cd '{dir}' && exec {shell} -l")
    };

    // `open -a Terminal` doesn't let us pass a startup command, so we use
    // osascript to drive Terminal.app directly.
    let script = format!(
        "tell application \"Terminal\"\n\
         activate\n\
         do script \"{cmd}\"\n\
         end tell"
    );
    Command::new("osascript")
        .args(["-e", &script])
        .spawn()?;
    Ok(())
}

#[cfg(target_os = "linux")]
fn open_linux(
    workspace: &Path,
    init_script: &Path,
    have_init: bool,
    shell: &str,
) -> std::io::Result<()> {
    let dir = workspace.to_string_lossy();
    let init_path = init_script.to_string_lossy();

    // Build the inner startup command. We pick a known shell binary
    // (bash/zsh/fish) so we can pass the right source flag —Terminal
    // emulators tend to expect `bash` by default.
    let (shell_bin, source_flag) = match shell {
        "fish" => ("fish", "-i"),
        "zsh" => ("zsh", "-l"),
        _ => ("bash", "-l"),
    };

    let startup = if have_init {
        format!("source '{init_path}' 2>/dev/null; cd '{dir}' && exec {shell_bin} {source_flag}")
    } else {
        format!("cd '{dir}' && exec {shell_bin} {source_flag}")
    };

    for terminal in [
        "x-terminal-emulator",
        "gnome-terminal",
        "konsole",
        "xfce4-terminal",
        "xterm",
    ] {
        let mut cmd = Command::new(terminal);
        match terminal {
            "gnome-terminal" => {
                cmd.args(["--", shell_bin, "-c", &startup]);
            }
            "konsole" => {
                cmd.args(["-e", shell_bin, "-c", &startup]);
            }
            "xfce4-terminal" => {
                cmd.args(["-x", shell_bin, "-c", &startup]);
            }
            "x-terminal-emulator" | "xterm" => {
                cmd.args(["-e", shell_bin, "-c", &startup]);
            }
            _ => {}
        }
        if cmd.spawn().is_ok() {
            return Ok(());
        }
    }
    Err(std::io::Error::new(
        std::io::ErrorKind::NotFound,
        "no supported terminal emulator found",
    ))
}
